title: Piotr Płaczek
subtitle: Node.js Developer
description: >-
  devlopr-jekyll is a beautiful Jekyll Theme Built For Developers, which is
  optimized for speed and readability.
url: ''
baseurl: ''
urls:
  # - text: About
  #   url: /about
author_logo: profile.jpg
author: Piotr Płaczek
author_bio: Piotr Płaczek bio
author_location: Poland
typewrite-text: Node.js developer
hero_cover_img: sample_cover.jpg
author_work_experiences:
  # - company_name: Google
  #   company_logo: google.png
  #   company_url: 'https://google.com'
  #   designation: Software Engineer
  #   description: Worked on various Google Products
  #   visibility: true
author_education_details:
  # - college_logo: mit.png
  #   college_name: MIT
  #   college_url: 'https://mit.org'
  #   college_degree: CS Engineer
  #   description: Bachelor of Technology
  #   visibility: true
author_project_details:
  # - project_thumbnail: gamershub.png
  #   project_title: Gamers Hub
  #   project_description: A Platform built for Gamers and Game Devs
  #   project_url: 'https://gamershub.in'
  #   visibility: true
linkedin_username: piotr-placzek
wakatime_username: piotr-placzek
olvy_organization: devlopr
olvy_widget_type: sidebar
markdown: kramdown
highlighter: rouge
permalink: pretty
show_author_work_experiences: true
show_author_education_details: true
show_author_project_details: true
paginate: 4
per_page: 4
paginate_path: '/blog/page/:num/'
collections: {}
defaults:
  - scope:
      path: gallery
    values:
      permalink: '/:path/:basename:output_ext'
  - scope:
      path: ''
      type: authors
    values:
      layout: author
      permalink: '/blog/authors/:slug'
  - scope:
      path: assets/**
    values:
      sitemap: false
plugins:
  - jekyll-paginate
  - jekyll-gist
  - jekyll-seo-tag
  - jekyll-sitemap
  - jekyll-admin
jekyll_admin:
  homepage: posts
exclude:
  - .sass-cache/
  - .jekyll-cache/
  - gemfiles/
  - Gemfile
  - Gemfile.lock
  - node_modules/
  - vendor/bundle/
  - vendor/cache/
  - vendor/gems/
  - vendor/ruby/
  - assets/bower_components/isotope-layout/README.md
  - assets/bower_components/icono/README.md
  - >-
    assets/bower_components/font-awesome/advanced-options/use-with-node-js/fontawesome-svg-core/README.md
  - assets/bower_components/ghosthunter/README.md
  - assets/bower_components/nanobar/README.md
  - assets/bower_components/lightgallery/demo/README.md
  - >-
    assets/bower_components/font-awesome/advanced-options/use-with-node-js/free-brands-svg-icons/README.md
  - >-
    assets/bower_components/font-awesome/advanced-options/use-with-node-js/free-solid-svg-icons/README.md
  - assets/bower_components/jquery-mousewheel/README.md
  - assets/bower_components/get-size/README.md
  - >-
    assets/bower_components/font-awesome/advanced-options/use-with-node-js/fontawesome/README.md
  - assets/bower_components/jquery-mousewheel/ChangeLog/README.md
  - >-
    assets/bower_components/font-awesome/advanced-options/use-with-node-js/fontawesome-free-regular/README.md
  - assets/bower_components/desandro-matches-selector/README.md
  - assets/bower_components/ev-emitter/README.md
  - assets/bower_components/font-awesome/README.md
  - >-
    assets/bower_components/font-awesome/advanced-options/use-with-node-js/fontawesome-free-solid/README.md
  - >-
    assets/bower_components/font-awesome/advanced-options/use-with-node-js/fontawesome-free/README.md
  - >-
    assets/bower_components/font-awesome/advanced-options/use-with-node-js/fontawesome-free-webfonts/README.md
  - >-
    assets/bower_components/font-awesome/advanced-options/use-with-node-js/fontawesome-free-brands/README.md
  - >-
    assets/bower_components/font-awesome/advanced-options/use-with-node-js/fontawesome-common-types/README.md
  - assets/bower_components/ghosthunter/example/Index.html
  - assets/bower_components/lightgallery/test/lightgallery.html
  - assets/bower_components/masonry-layout/README.md
  - assets/bower_components/imagesloaded/README.md
destination: ./build
